import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Using Inter as standard font
import "./globals.css";
import { Sidebar, Header } from "@/components/ui/layout-components";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin", "vietnamese"] });

export const metadata: Metadata = {
  title: "TitanLabs Clone",
  description: "Generated by Antigravity",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi">
      <body className={cn(inter.className, "bg-gray-50 min-h-screen text-slate-900 font-sans")}>
        <div className="flex min-h-screen">
          <Sidebar />
          <div className="flex-1 flex flex-col min-w-0">
            <Header />
            <main className="flex-1 lg:ml-64 p-6 overflow-y-auto">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
